/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author manuel
 */
public class CentroJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CentroJFrame
     */
    public CentroJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        localidadTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cpTextField = new javax.swing.JTextField();
        direccionTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        provinciaTextField = new javax.swing.JTextField();
        nombreTextField = new javax.swing.JTextField();
        cifTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        telefonoTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        faxTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        responsableTextField = new javax.swing.JTextField();
        cancelarButton = new javax.swing.JButton();
        aceptarButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        anexo0JTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("CIF");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        jLabel4.setText("Nombre del centro");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        jLabel5.setText("Dirección");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        jLabel6.setText("Localidad");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 20));

        localidadTextField.setText("localidadTextField");
        getContentPane().add(localidadTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 150, -1));

        jLabel7.setText("C.P.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, 20));

        cpTextField.setText("cpTextField");
        getContentPane().add(cpTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 70, -1));

        direccionTextField.setText("direccionTextField");
        getContentPane().add(direccionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 460, -1));

        jLabel8.setText("Provincia");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, 20));

        provinciaTextField.setText("provinciaTextField");
        getContentPane().add(provinciaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 120, -1));

        nombreTextField.setText("nombreTextField");
        nombreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nombreTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 460, -1));

        cifTextField.setText("cifTextField");
        cifTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cifTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(cifTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 110, -1));

        jLabel1.setText("Teléfono");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 30));

        telefonoTextField.setText("telefonoTextField");
        getContentPane().add(telefonoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 100, -1));

        jLabel2.setText("Fax");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, 20));

        faxTextField.setText("faxTextField");
        getContentPane().add(faxTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 90, -1));

        jLabel9.setText("E-Mail");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, 20));

        emailTextField.setText("emailTextField");
        getContentPane().add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 170, -1));

        jLabel10.setText("Director/a");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 30));

        responsableTextField.setText("responsableTextField");
        getContentPane().add(responsableTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 220, -1));

        cancelarButton.setText("Cancelar");
        getContentPane().add(cancelarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, -1, -1));

        aceptarButton.setText("Aceptar");
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(aceptarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Plantillas"), "Plantillas"));

        jLabel11.setText("Anexo 0");

        jButton1.setText("Buscar...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anexo0JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anexo0JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(3, 3, 3))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 600, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cifTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cifTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cifTextFieldActionPerformed

    private void nombreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextFieldActionPerformed

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aceptarButtonActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JTextField anexo0JTextField;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JTextField cifTextField;
    private javax.swing.JTextField cpTextField;
    private javax.swing.JTextField direccionTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField faxTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField localidadTextField;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JTextField provinciaTextField;
    private javax.swing.JTextField responsableTextField;
    private javax.swing.JTextField telefonoTextField;
    // End of variables declaration//GEN-END:variables
}
